Clean up Makefile output

diff --git a/projects/01/Makefile b/projects/01/Makefile
--- a/projects/01/Makefile
+++ b/projects/01/Makefile
@@ -6,9 +6,15 @@ all:
 test: $(PROGRAMS)
 
 $(PROGRAMS):
-	$(SIMULATOR) $@.tst
+	@echo "Testing $@.tst"
+	@OUTPUT="$(shell $(SIMULATOR) $@.tst 2>&1)"; \
+	if echo "$$OUTPUT" | grep -q "failure"; then \
+		echo "$$OUTPUT from $@.tst" ; \
+		exit 1; \
+	fi
 
 .PHONY: clean
 
 clean:
-	rm -f *.out
+	@echo "Cleaning projects/01"
+	@rm -f *.out
diff --git a/projects/03/Makefile b/projects/03/Makefile
--- a/projects/03/Makefile
+++ b/projects/03/Makefile
@@ -6,10 +6,16 @@ all:
 test: $(PROGRAMS)
 
 $(PROGRAMS):
-	$(SIMULATOR) $@.tst
+	@echo "Testing $@.tst"
+	@OUTPUT="$(shell $(SIMULATOR) $@.tst 2>&1)"; \
+	if echo "$$OUTPUT" | grep -q "failure"; then \
+		echo "$$OUTPUT from $@.tst" ; \
+		exit 1; \
+	fi
 
 .PHONY: clean
 
 clean:
-	rm -f a/*.out
-	rm -f b/*.out
+	@echo "Cleaning projects/03"
+	@rm -f a/*.out
+	@rm -f b/*.out
diff --git a/projects/04/Makefile b/projects/04/Makefile
--- a/projects/04/Makefile
+++ b/projects/04/Makefile
@@ -7,12 +7,18 @@ all:
 test: $(PROGRAMS)
 
 $(PROGRAMS):
-	$(EMULATOR) $@.tst
+	@echo "Testing $@.tst"
+	@OUTPUT="$(shell $(EMULATOR) $@.tst 2>&1)"; \
+	if echo "$$OUTPUT" | grep -q "failure"; then \
+		echo "$$OUTPUT from $@.tst" ; \
+		exit 1; \
+	fi
 
 .PHONY: clean
 
 clean:
-	rm -f fill/*.hack
-	rm -f fill/*.out
-	rm -f mult/*.hack
-	rm -f mult/*.out
+	@echo "Cleaning projects/04"
+	@rm -f fill/*.hack
+	@rm -f fill/*.out
+	@rm -f mult/*.hack
+	@rm -f mult/*.out
diff --git a/projects/07/C++/Makefile b/projects/07/C++/Makefile
--- a/projects/07/C++/Makefile
+++ b/projects/07/C++/Makefile
@@ -15,29 +15,38 @@ all: builddir $(VM_TRANSLATOR)
 test: builddir $(PROGRAMS)
 
 $(PROGRAMS): $(VM_TRANSLATOR)
-	$(VM_TRANSLATOR) $@.vm
-	$(EMULATOR) $@.tst
+	@echo "Testing $@.tst"
+	@$(VM_TRANSLATOR) $@.vm
+	@OUTPUT="$(shell $(EMULATOR) $@.tst 2>&1)"; \
+	if echo "$$OUTPUT" | grep -q "failure"; then \
+		echo "$$OUTPUT from $@.tst" ; \
+		exit 1; \
+	fi
 
 $(VM_TRANSLATOR): $(OBJS)
-	$(CXX) $(CXXFLAGS) $^ -o $@
+	@echo "Linking $(notdir $@)"
+	@$(CXX) $(CXXFLAGS) $^ -o $@
 
 bin/%.o: src/%.cpp
-	$(CXX) $(CXXFLAGS) -I$(INCLUDE_FOLDER) -c $^ -o $@
+	@echo "Compiling $(notdir $@)"
+	@$(CXX) $(CXXFLAGS) -I$(INCLUDE_FOLDER) -c $^ -o $@
 
 .PHONY: clean builddir
 
 clean:
-	rm -rf bin/
-	rm -f ../StackArithmetic/SimpleAdd/*.out
-	rm -f ../StackArithmetic/SimpleAdd/*.asm
-	rm -f ../StackArithmetic/StackTest/*.out
-	rm -f ../StackArithmetic/StackTest/*.asm
-	rm -f ../MemoryAccess/BasicTest/*.out
-	rm -f ../MemoryAccess/BasicTest/*.asm
-	rm -f ../MemoryAccess/PointerTest/*.out
-	rm -f ../MemoryAccess/PointerTest/*.asm
-	rm -f ../MemoryAccess/StaticTest/*.out
-	rm -f ../MemoryAccess/StaticTest/*.asm
+	@echo "Cleaning projects/07/C++"
+	@rm -rf bin/
+	@rm -f ../StackArithmetic/SimpleAdd/*.out
+	@rm -f ../StackArithmetic/SimpleAdd/*.asm
+	@rm -f ../StackArithmetic/StackTest/*.out
+	@rm -f ../StackArithmetic/StackTest/*.asm
+	@rm -f ../MemoryAccess/BasicTest/*.out
+	@rm -f ../MemoryAccess/BasicTest/*.asm
+	@rm -f ../MemoryAccess/PointerTest/*.out
+	@rm -f ../MemoryAccess/PointerTest/*.asm
+	@rm -f ../MemoryAccess/StaticTest/*.out
+	@rm -f ../MemoryAccess/StaticTest/*.asm
 
 builddir:
-	mkdir -p $(dir $(VM_TRANSLATOR))
+	@echo "Testing projects/07/C++"
+	@mkdir -p $(dir $(VM_TRANSLATOR))
